name: Run meta pytest suite on repo

on:
  pull_request:
  push:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-test:
    if: ${{ endsWith(github.repository, '-auto-template')  }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          ref: ${{ github.head_ref }}

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - uses: astral-sh/setup-uv@v6

      - name: Install meta-test dependencies
        run: uv pip install --system pytest cookiecutter

      - name: run pytest
        env:
          UPDATE_TO_LATEST: 'False'
        run: uv run --no-project python -m pytest
